_projeto/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import  static
from .settings import MEDIA_URL, MEDIA_ROOT
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from carro.views import principal

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', principal, name='home'),
    path('', include('carro.urls')),
    path('', include('accounts.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views 
from .views import *


app_name = 'carro'

urlpatterns = [
    path('inicial/', views.principal, name='inicial'),
    path('cadastro_veiculo/', Cadastrar_veiculo.as_view(), name='cadastro_veiculo'),
    path('abastecer/', Abastecer_veiculo.as_view(), name='abastecer_veiculo'),
    path('despesas/', Despesas.as_view(), name='despesas_veiculo'),
    path('troca_oleo/', Troca_Oleo.as_view(), name='troca_oleo'),
    path('usuario/', views.usuario, name='usuario'),
    path('logout',views.logout_view,name='logout'),
]

carro/models.py
from django.db import models
from accounts.models import User

class TipoCombustivel(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

class Veiculo(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="veiculos")
    marca = models.CharField(max_length=20)
    nome = models.CharField(max_length=20)
    modelo = models.CharField(max_length=20)
    placa = models.CharField(max_length=9)
    ano = models.IntegerField()
    tanque = models.IntegerField()
    tipo_combustivel = models.ForeignKey(TipoCombustivel, on_delete=models.DO_NOTHING)
    odometro = models.FloatField()
    renavam = models.CharField(max_length=11)

    def __str__(self):
        return self.placa

class Abastecer(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    placa = models.ForeignKey(Veiculo, on_delete=models.DO_NOTHING)
    data = models.CharField(max_length=10)
    odometro = models.FloatField()
    tipo_combustivel = models.ForeignKey(TipoCombustivel, on_delete=models.DO_NOTHING)
    qtd_litros = models.FloatField()
    completo = models.BooleanField(default=False)
    preco = models.FloatField()
    valor_total = models.FloatField()
    posto = models.CharField(max_length=20)

class TipoDespesa(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Despesa(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    placa = models.ForeignKey(Veiculo, on_delete=models.DO_NOTHING)
    opcao = models.ForeignKey(TipoDespesa, on_delete=models.DO_NOTHING)
    valor = models.FloatField()
    odometro = models.FloatField()
    data = models.CharField(max_length=10)
    local = models.CharField(max_length=50)
    observacao = models.CharField(max_length=144, blank=True)

    def __str__(self):
        return self.observacao

class Troca_Oleo(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    placa = models.ForeignKey(Veiculo, on_delete=models.DO_NOTHING)
    data = models.CharField(max_length=10)
    km_atual = models.FloatField()
    proxima_troca = models.FloatField()
    filtro_oleo = models.BooleanField(default=True)

carro/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class FormularioVeiculo(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(FormularioVeiculo, self).__init__(*args, **kwargs)
    class Meta:
        model = Veiculo
        fields = ['marca','nome','modelo','placa','ano','tanque','tipo_combustivel','odometro','renavam',]


class CustomModelFilter(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return "%s" % (obj.placa)


class FormularioAbastecimento(ModelForm):
    filtro_oleo = forms.BooleanField(widget=forms.CheckboxInput, required=False, initial=False, label='Encheo o tanque: ')  

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(FormularioAbastecimento, self).__init__(*args, **kwargs)
        self.fields['placa'] = CustomModelFilter(queryset=Veiculo.objects.filter(usuario=self.request.user))
    class Meta:
        model = Abastecer
        fields = ['placa', 'data', 'odometro', 'tipo_combustivel', 'qtd_litros', 'completo', 'preco', 'valor_total',
                  'posto']
        

class FormularioDespesas(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        print(self.request.user.veiculos)
        super(FormularioDespesas, self).__init__(*args, **kwargs)
        self.fields['placa'] = CustomModelFilter(queryset=Veiculo.objects.filter(usuario=self.request.user))
    class Meta:
        model = Despesa
        fields = ['placa', 'opcao','valor','odometro', 'data','local','observacao',]
    

class FormularioTrocaOleo(forms.ModelForm):
    filtro_oleo = forms.BooleanField(widget=forms.CheckboxInput, required=False, initial=False, label='Troca de óleo: ')  

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(FormularioTrocaOleo, self).__init__(*args, **kwargs)
        self.fields['placa'] = CustomModelFilter(queryset=Veiculo.objects.filter(usuario=self.request.user))
    class Meta:
        model = Troca_Oleo
        fields = ['placa', 'data','km_atual','proxima_troca','filtro_oleo']

carro/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from .forms import *
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

def principal(request):
    return render(request, 'inicial.html')

class Cadastrar_veiculo(LoginRequiredMixin, CreateView):
    model = Veiculo
    form_class = FormularioVeiculo
    success_url = reverse_lazy('carro:cadastro_veiculo')
    template_name = 'carro/cadastro_veiculo.html'
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        url = super().form_valid(form)

        return url

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

class Abastecer_veiculo(LoginRequiredMixin, CreateView):
    model = Abastecer
    form_class = FormularioAbastecimento
    success_url = reverse_lazy('carro:abastecer_veiculo')
    template_name = 'carro/abastecimento.html'
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.usuario = self.request.user

        url = super().form_valid(form)

        return url

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

class Despesas(LoginRequiredMixin, CreateView):
    model = Despesa
    form_class = FormularioDespesas
    success_url = reverse_lazy('home')
    template_name = 'carro/despesas.html'
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.usuario = self.request.user

        url = super().form_valid(form)

        return url

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

class Troca_Oleo(LoginRequiredMixin, CreateView):
    model = Troca_Oleo
    form_class = FormularioTrocaOleo
    success_url = reverse_lazy('home')
    template_name = 'carro/troca_oleo.html'
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.usuario = self.request.user

        url = super().form_valid(form)

        return url
        
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


def usuario(request):
    return render(request, 'carro/tela.html')

def logout_view(request):
    logout(request)
    return redirect('carro:inicial')

templates/carro/abastecimento.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}OnTheRoad{% endblock %}
{% block link %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="stylesheet" href="{% static 'css/style-abastecer.css' %}">
{% endblock %}
{% block pagina %}ABASTECIMENTO{% endblock %}
{% block content %}
    <div class="form">
        <form action="" method="post" id="form-cadastrar">
            {% csrf_token %}
            {{ form.placa|as_crispy_field }}
            {{ form.data|as_crispy_field }}
            {{ form.odometro|as_crispy_field }}
            {{ form.tipo_combustivel|as_crispy_field }}
            {{ form.qtd_litros|as_crispy_field }}
            {{ form.preco|as_crispy_field }}
            {{ form.valor_total|as_crispy_field }}
            {{ form.posto|as_crispy_field }}
            <div class="mb-3"> 
                <div id="div_id_filtro_oleo" class="mb-3"> 
                    <label for="id_filtro_oleo" class="form-check-label">Encheu o tanque: </label>
                    <input type="checkbox" name="filtro_oleo" class="checkboxinput form-check-input" id="id_filtro_oleo" checked> 
                </div>
            </div>
            <input type="submit" value="Entrar">
        </form>
    </div>
{% endblock %}

templates/carro/cadastro_veiculo.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}OnTheRoad{% endblock %}
{% block link %}
<link rel="stylesheet" href="{% static 'css/style-cadastro-car.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
{% endblock %}
{% block pagina %}CADASTRO DE VEÍCULO{% endblock %}
{% block content %}
    <div class="form">
        <form action="" method="post" id="form-cadastrar">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Entrar">
        </form>
    </div>
{% endblock %}

templates/carro/despesas.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}OnTheRoad{% endblock %}
{% block link %}
<link rel="stylesheet" href="{% static 'css/style-despesa.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
{% endblock %}
{% block pagina %}DESPESAS{% endblock %}
{% block content %}
    <div class="form">
        <form action="" method="post" id="form-cadastrar">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Entrar">
        </form>
    </div>
{% endblock %}

templates/carro/tela.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static 'css/tela.css' %}">
    <title>OnTheRoad</title>
</head>
<body>
    <header>
        <h1>TELA USUÁRIO</h1>
    </header>
    <input type="checkbox" id="check">
    <label for="check" class="check">
        <img src="{% static 'imagem/menuu.png' %}" alt="">
    </label>
    <nav class="menu">
        <ul>
            <li> <a href="{% url 'carro:usuario' %}">Home</a></li>
            <li> <a href="{% url 'carro:cadastro_veiculo' %}">Cadastrar veículo</a></li>
            <li> <a href="{% url 'carro:abastecer_veiculo' %}">Abastecer</a></li>
            <li> <a href="{% url 'carro:troca_oleo' %}">Troca de óleo</a></li>
            <li> <a href="{% url 'carro:despesas_veiculo' %}">Despesas</a></li>
            <li> <a href="{% url 'carro:logout'%}">Logout</a></li>
        </ul>
    </nav>

 </body>
</html>

templates/carro/troca_oleo.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}OnTheRoad{% endblock %}
{% block link %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="stylesheet" href="{% static 'css/style-troca-oleo.css' %}">
{% endblock %}
{% block pagina %}TROCA DE ÓLEO{% endblock %}
{% block content %}
    <div class="form">
        <form action="" method="post" id="form-cadastrar">
            {% csrf_token %}
            {{ form.placa|as_crispy_field }}
            {{ form.data|as_crispy_field }}
            {{ form.km_atual|as_crispy_field }}
            {{ form.proxima_troca|as_crispy_field }}
            <div class="mb-3"> 
                <div id="div_id_filtro_oleo" class="mb-3"> 
                    <label for="id_filtro_oleo" class="form-check-label">Troca de filtro: </label>
                    <input type="checkbox" name="filtro_oleo" class="checkboxinput form-check-input" id="id_filtro_oleo" checked> 
                </div>
            </div>
            <input type="submit" value="Entrar">
        </form>
    </div>
{% endblock %}